name: SpawnMob
version: '${project.version}'
main: net.skylyfe.plugins.spawnmob.Main
api-version: 1.17
authors: [ jakka12, amarstang ]
description: Advanced /spawnmob command.
website: https://skylyfe.net

commands:
  spawnmob:
    description: Your description
    usage: /<command> <entity>
    permission: spawnmob.use
